cat('Weighted regression for estuaries...','\n')

library('maptools')
library('raster')
library('rgdal')
library('scales')
library('reshape')
library('RColorBrewer')
library('ggplot2')
library('quantreg')
library('rgeos')
library('gridExtra')
library('Metrics')
library('gtable')
library('Hmisc')

source('wtreg_funs.r')
load('tb_dat.RData')